import './globals.css'
import type { Metadata } from 'next'
import Header from "@/components/Header";
import SocialLinks from "@/components/social_links/SocialLinks";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-fixed bg-gradient-to-b from-black from-10% to-gunmetal">
          <Header/>
          <SocialLinks/>
          <main>
            {children}
          </main>
      </body>
    </html>
  )
}
