name: Lint Codebase

on: 
  push:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Codebase
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASES: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_HTML: true